### ISSUE TITLE
Create non-root users on droplet

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#10]
Per https://www.digitalocean.com/community/tutorials/initial-server-setup-with-ubuntu-16-04

create:

- jay
- ed
- www

**Comment by emazurek** [comment]
after I ssh into the server as root, here are the commands I used to create new users.

```sh
adduser jay # prompts for new user password -- will e-mail
usermod -aG sudo jay # give jay sudo permissions


su jay # change user to jay
mkdir ~/.ssh && touch ~/.ssh/authorized_keys
# add ssh keys from existing ssh config for ssh login
sudo cat /root/.ssh/authorized_keys > ~/.ssh/authorized_keys 
```
now you can log into the server avoiding root with `ssh jay@159.89.55.244`

I can e-mail you the sudo password for jay

**Comment by emazurek** [comment]
Added jay and ed to superuser group. Not 100% sure if I'll need to add www as a superuser as well. Closing this for now.

**Comment by emazurek** [comment]
Changing `jay` to `jrush`

**Comment by emazurek** [comment]
```sh
sudo usermod -l jrush jay
sudo usermod -d /home/jrush -m jrush
```

**Comment by tjayrush** [comment]
I confirm that this works and that I can both login as `jrush` and `sudo` with the password provided. Thanks.
