### ISSUE TITLE
install nginx

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#11]
Let's use nginx to serve websites (specifically tokenomics) from our server.

Remember to document steps.

**Comment by emazurek** [comment]
Instructions in [DigitalOcean blog post](https://www.digitalocean.com/community/tutorials/how-to-install-nginx-on-ubuntu-16-04). Here's what I did:

```sh
# Install nginx
sudo apt-get update
sudo apt-get install nginx

# Allow through firewall
sudo ufw allow 'Nginx Full'

# create tokenomics.io www folder
sudo mkdir -p /var/www/tokenomics.io/html

# configure default server block to point to /var/www/tokenomics.io/html
sudo nano /etc/nginx/sites-enabled/default
```

**Comment by tjayrush** [comment]
I'm just adding this here for my reference: https://www.digitalocean.com/community/tutorials/apache-vs-nginx-practical-considerations
