### ISSUE TITLE
Get ssl certificate for tokenomics.io

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#12]
This will allow us to serve tokenomics.io over https

Document steps.

**Comment by emazurek** [comment]
Per [DigitalOcean blog post](https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04):

We'll use the letsencrypt.org certbot to keep our ssl certificate refreshed.

```sh
sudo add-apt-repository ppa:certbot/certbot
sudo apt-get update
sudo apt-get install python-certbot-nginx
sudo certbot --nginx -d tokenomics.io -d www.tokenomics.io
```

**Comment by tjayrush** [comment]
I confirm that https://tokenomics.io works. Thanks.
