### ISSUE TITLE
Upload simple tokenomics splash page

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#13]
And leave simple documentation

**Comment by emazurek** [comment]
Simple little splash page.

On server, files contained at `/var/www/tokenomics.io/html`

**Comment by tjayrush** [comment]
Will the files that make up the website ultimately be in GitHub?

**Comment by emazurek** [comment]
Yep, you can see the splash page in the repo, it's in the
front-end/temp-splash folder.
