### ISSUE TITLE
Install google analytics and provide access instructions

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#14]

**Comment by tjayrush** [comment]
I have a google analytics account for quickBlocks. I'd like to use the same account (or at least one we can tie to the same account). I will dig up information and post it here.

**Comment by emazurek** [comment]
Created a new Google Analytics property for tokenomics.io. You'll have full access under your quickblocks account. I've tested it on the splash page and have ensured traffic is recorded properly.

![screen shot 2018-02-28 at 10 43 52 pm](https://user-images.githubusercontent.com/5423313/36826057-e87ed692-1cd8-11e8-8bf2-177bc89b0676.png)
