### ISSUE TITLE
Write basic API retrieving basic data from mysql database

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#29]

**Comment by emazurek** [comment]
Reverse proxy steps at bottom: https://www.digitalocean.com/community/tutorials/how-to-set-up-a-node-js-application-for-production-on-ubuntu-16-04

**Comment by emazurek** [comment]
Very basic API hitting our mysql test database to get nobel prizewinner data: https://tokenomics.io/api/test/nobel

**Comment by emazurek** [comment]
Very basic api up: https://tokenomics.io/api/test/nobel

Will commit code to repo.

**Comment by tjayrush** [comment]
The reverse proxy part of the bottom of the first article is very interesting. It might benefit us to have separate 'apps' (as they describe them). In this way, maybe there's one api called http://tokenomics.io/apis/accounts and another called http://tokenomics.io/apis/blocks and each can be its own application. As things get more complex, this might make it easier to work on one part of the API vs. another.
