### ISSUE TITLE
Define initial tokens of interest

### ISSUE THREAD

**Issue by emazurek** [Great-Hill-Corporation/tokenomics#3]
I think you mentioned these:
- Augur
- Quantstamp
- Giveth
- (others you mentioned)

**Comment by tjayrush** [comment]
|-----|------|
| **Group 1:**||
|- etherTip|community interest|
|- ENS|community interest|
|- dao|historical interest, plus I have used as test case for a long time so I know it's correct|
|- giveth_ff|want to give back to this group|
|- quantstamp|potential client|
|- augur|long lived, lots of transactions|
|||
|**Group 2:**||
|- gnosis|lots of transactions|
|- binance|lots of transactions|
|- Bancor|lots of transactions|
|- maker|very interesting project|
|- rchain|very interesting project|
|||
|**Group 3:**||
|- firstAcct|first account every to create a transaction on network|
|- tierion|very active contract|
|- tenX|very active|
|- FundYourNetwork|interesting project|
|- singular|very old account with lots of transactions during Sept. 2016 Ddos attack - good test case|
|- firstBlood|very old account with lots of transactions |
|- paritySMS|community interest (the data here may be of particular interest)|
|- expertyHack|example of a hacked contract|
|- whiteHat|community interest|

**Comment by emazurek** [comment]
Thanks Jay.
