### ISSUE TITLE
email to tokenomics

### ISSUE THREAD

**Issue by tjayrush** [Great-Hill-Corporation/tokenomics#9]
info@
sales@
support@

should all send to corresponding @quickblocks.io

**Comment by emazurek** [comment]
Per [this blog post](http://www.kevinsweet.com/forwarding-email-digital-ocean-ubuntu), set up mail forwarding from tokenomics.io to quickblocks.io. Sent test e-mails to:

- info@
- sales@
- support@
- madeupemail@ (already got mail delivery subsystem error)

**Comment by emazurek** [comment]
@tjayrush confirmed emails went through.
